#!/bin/sh

SCRIPT_DIR="$(cd "$(dirname "$(readlink "$0" || echo "$0")")" && pwd -P)"
LIBS_DIR="${SCRIPT_DIR}/../lib"
JAVA="${JAVA:-java}"

$JAVA -cp $(find $LIBS_DIR -type f | tr '\n' ':') cz.rdc.devel.jabber.migrate.Main $@
